### ISSUE TITLE
TypeError: __init__() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Kfmoss** [kidscancode/pygame_tutorials#7]
Hello, I can't run it. (windows 10, python3.8, pygame 1.9)
pygame_tutorials/tilemap/part 06/main.py /

I got this on the terminal:
       Wall(self, col, row)
TypeError: __init__() takes 2 positional arguments but 4 were given.
I suspect that there's something wrong in the Wall class in tilemap.py?

or maybe is just my python/pygame version?

**Comment by cbscribe** [comment]
This means that when you defined `class Wall`, you defined it with a different number of arguments than when you called it.

In this section, Wall is defined by:
```
class Wall(pg.sprite.Sprite):
    def __init__(self, game, x, y):
```
I suspect you have something different.

**Comment by Kfmoss** [comment]
Ohhh. Thank you! :)
