### ISSUE TITLE
Error in shmup-11.py

### ISSUE THREAD

**Issue by j-tesla** [kidscancode/pygame_tutorials#8]
In [shmup-11.py](https://github.com/kidscancode/pygame_tutorials/blob/master/shmup/shmup-11.py),

**Traceback (most recent call last):
  File "/home/strange/Documents/learn_py/my-pygame/shmup.py", line 290, in <module>
    if not player.lives == 0 and not death_explosion.alive():
NameError: name 'death_explosion' is not defined**

@kidscancode , take a look!

**Comment by cbscribe** [comment]
`death_explosion` is defined on line 276 of this part. I suspect your problem is the extra `not` in this line - you're checking if the player *is* alive, not if it's dead.
